# Base configs
baseurl: "https://yiran.github.io/foto"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Yiran"
subtitle: "See the world through my eyes!"
author: "Yiran"
header:
 title: "Photography"
 subtitle: "by Yiran"
footer:
 name: "Hey there, my name is Yiran"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork this repo on github</a> ;)"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ravenfrank_m/"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://www.linkedin.com/in/yiran-mao-6aba26233/"
  github: "https://github.com/yiran-frank-mao"
